os: linux
dist: bionic
language: python
python:
- '3.7'
- '3.8'

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install:
- pip install ".[test]"

script:
- pytest .
- mypy --ignore-missing-imports src

deploy:
  - provider: pypi
    username: "__token__"
    password:
      secure: "JTYSK5XfpKdXr07sItSFbdY5/xzR24JvV5pfMtK2k7CmVtda4+ldcWbVdtUJQldkniODiKDyxD/kPorLXy/u2mxszf0IwR82eSZectKZuC8WpcfKMTMiwPu+lTYy94byjbWU7G7+2lE2Zzodz8ANWqrIZqpEyLsQrV4vUf2FbAk5swePaakTlm0K9wDS5699zRoN7kgRrf7I2VYZ1BTOmpvRoUJAGmuDHS/3O7TttJv/uJOC50f9cZUbqhGIdX6ATkiuMqVlceybfhDO3ibuv61D3OaPr7hLFrNsa8tfWpfaJIcPu1YTcoPcKVeBk94+IATx4RxneBlhBuz0WrfRoC5GDmj28E3vREThl3pDIZejNH2XQrFTnXfyifv5B0LRU141cKRMb3S+zKT9Npv60Kn6adjrJFtt2hSPRe4SLX2z2PaaglvqR067LvzVY+gKD9chsLcAQmsj6fDF+mVYj9h0xK/EnULXQYaLZC4VNYlDvduqJZCgGhZWZmStgj1YOCKfEzkhxRMZllUPxxzoHpy/+tPWWECnyx2hxXl+uIP8fVOQixH3keX7o6xyrNFxhwhWDh6ZYWlZ1dhV92RuYBthC1vLQjzWeCZKSvCC2RwTXaWqoeGvcS5p7midGmu7NVpi4B8Mx0GdnCQXSi8P/nBz+kddq/WmSu+jt1tD/ro="
    on:
      tags: true
    skip_existing: true
  - provider: script
    script: "bash conda-build/travis_deploy.sh"
    on:
      tags: true
