os: linux
dist: bionic
language: python
python:
- '3.7'
- '3.8'

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install:
- pip install ".[test]"

script:
- pytest .
- mypy --ignore-missing-imports src

deploy:
  - provider: pypi
    username: __token__
    password:
      secure: i0PmFwh6poJoK11Fsmp+k0TGB/+1DtrCKl9r76Tp5Ql2tScWhGjW4PrJrOLH3RHSk7zhUiTDWCkhJdQt3HLVpOx5nybEJ4Qe6v8Z1YtRgj0V8u1k6kuvEZ5flazJm+6sGSQPPW9nEL1BQm6dDhxvAlU4bs/tVyiK86m6GOyvjI4Xee+O6d4AlRR8F5JgHgqsw787q7ze9SacSvuJh1mks7qKhsrPTsF0h4lsfR0h7WteaHPGIi5ETI9yw4t2OQcpaseFio5+r9JIntiVmz6ghK7TuqD49XjzGCzAd/ZK68dSNxKujV5JrtP3W5ysBPj5IX7YfhYllcSMjEB5TN5RjQ7pL17puEqJ3n32I2Sl+GH+wluMj0W9gbqKUkd4uxdIfSJl38MSndlaNhhSOPAt7p4ogpUsh5HSMI4/Fh/ZT7+QJz2f5UXY6ZtREdDjLrgcoT+1aLGBDqY/PUfGY3bILx0+BZWjSE+ke0OCK0mb/0hNwtobTFwjcEeWxbsp7hDpxiH3EnaK23if1Qyog7Vj5wkcVsxdh7Ir7mecz5j8uSsKhaaxaVLLZHJUn12zJcct3ER2p2sjmeIerlAb2eODYeI1SCPQ+oGw0e+rzqVnm8xhJSl24uBXrH+KPpQdSNbJjekOj7Db/z5qEbW/GUoYI4R4ahf3H5zALneAl0arJxY=
    on:
      tags: true
    skip_existing: true
  - provider: script
    script: "bash conda-build/travis_deploy.sh"
    on:
      tags: true
