dist: bionic
language: python
python:
- '3.7'
- '3.8'

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install:
- pip install ".[test]"

script:
- pytest .
- mypy --ignore-missing-imports src

deploy:
  - provider: pypi
    username: "__token__"
    password:
      secure: df5aJ+C3WEMfjp/yNwQgH0eQJMVR2wQdcgbMO0jWux7EGb1f6PZhHTc8n7w6eSrsqLnFS5VWqHXXHWtgd5eX0Cu/hqPY3Xr8z9TwfLvyHlvT+YDMnhMRNI+CEz05Fabl8ioHozDjoqTC55hqWqxaR7dZUS0tlfcMLMu+RPNhPadcdbOwWDz5+cLCPnB7fxUJBu0rMNw+R9avO67yBqniyWY/C8WHfLNn2opu9q1tafrGRTlHHbU0j22vSq0msblOXdedbtd1bsrOna2V8X194HSrFcIoqoWzmgiHuNop6KRgFVQqIO2yZsd5eqwbMpX+KVsiRK17k9lZqkVQR1WAK1xPxB18g1E5E2AVgr+GdMqBzCr43GAYhXqWDJp2nGymdXVBfcfg0Aq+0tHyPCxGY3c/D44/Ic+yzIEPCixc6KABlCS/OIDIoSFQwU2DpRNDfJp9Yjy7HYjN2UxH6Ych3gV96OUNx4pK1iqSPg1sOtZfWIbw9NyvdaSwxlpaCHCHh9InwrrnoTA1KrvsE2MdEmMnJ+4u/f74zv6zX3VD6yKTYiVe09DiYuvCEggwVOZHR7mywQLvkYhmkf4zB/nzV36DGLd9X8Zz5bg6NiR+707Jic8MQM6cIayFJY5xLh5BwoF9sJ0bMPN3oDkQouUU03XBmnYaethj4CLk89xxUqk=
    on:
      tags: true
    skip_existing: true
  - provider: script
    script: "bash conda-build/travis_deploy.sh"
    on:
      tags: true
