os: linux
dist: bionic
language: python
python:
- '3.7'
- '3.8'

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install:
- pip install ".[test]"

script:
- pytest .
- mypy --ignore-missing-imports src

deploy:
  - provider: pypi
    username: "__token__"
    password:
      secure: "eLp1CCiwIRlmZCvSGkmaCLdQxJ8urLDfVY+AKtlzefXaHaCEVY5GOrTJ2qXL3WGzgwDxDWm2fjGSoKONR1Cgw7TyBZ3OdVbMLaxeCTKU4KDPdaUFbcDXqbhviPoB0/0HX+LhhTwQ33sxTccgJ98OAlwHFNo26v0+8nizn7dOVfNQdO0B+aY00CNNZbpv9kpCIhk3axoqbDNGzZMZZG3zDkr+PjasOFH3Xam1R8CkN3738nQIl0FYLB5Yy0nXgWd5/6YS2kRc9B1khxQnlIXNjDJrYbdVG1lmjdC7mDuCzPg8rSTxLk0UgXQIZGGKeRDzKXDm7I+GZHtm+BNuOzgjfALwzbVEQux9zzjM6f96bOPzZBT/qes5TKbTpTw+dq246zK9i7XkOJckIs8PVqGSfve/vhnbUIKa/S2+7PoWQko6HrEo63lJhrBV2Fh6IZBzrRu5hBE49/Xt4AcZ2FhcnyPEjuRhSJSbhCYBC2YwQy86iubZy4MLoh5ETeBH2VjE097dRFCa9FXlK/iQhslTbwH0qOmlzGrTzVuTptc3E1OQVBv/VzVmOUqLWYbsF05CMTB547Nytq3Pqe5i9J0JQsPy1QnbehO1+d4D2jLh64rBO3PLWzux6KBzMuOJRNHjqRa8+Ct/F8nlHBKpGu0yXRGEhrRC0Hhm+NOvYc8drAc="
    on:
      tags: true
    skip_existing: true
  - provider: script
    script: "bash conda-build/travis_deploy.sh"
    on:
      tags: true
