dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install:
- pip install ".[test,dev]"

script:
- mypy --ignore-missing-imports predector

deploy:
  - provider: pypi
    user: "__token__"
    password:
      secure: test
    on:
      tags: true
    skip_existing: true

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
  skip_existing: true
