{% set name = "predector-utils" %}
{% set url = "https://github.com/ccdmb/predector-utils" %}
{% set description = "Utilities to run the predector pipeline." %}

{% set data = load_setup_py_data() %}

package:
  name: "{{ name | lower }}"
  version: "{{ data['version'] }}"

source:
  path: "../"

build:
  entry_points:
    - predector=predector.main:main
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python

test:
  imports:
    - predector
    - test
  commands:
    - predector --help
  requires:
    - pytest

about:
  home: "{{ url }}"
  license: BSD
  license_family: BSD
  license_file: "LICENSE"
  summary: "{{ description }}"
  doc_url: "{{ url }}"
  dev_url: "{{ url }}"

extra:
  maintainers:
    - Darcy Jones <darcy.a.jones@postgrad.curtin.edu.au>
  recipe-maintainers:
    - darcyabjones
