{% set name = "predectorutils" %}
{% set url = "https://github.com/ccdmb/predector-utils" %}
{% set description = "Utilities to run the predector pipeline." %}

{% set data = load_setup_py_data() %}

package:
  name: "{{ name | lower }}"
  version: "{{ data['version'] }}"

source:
  path: "../"

build:
  noarch: python
  entry_points:
    - predutils=predectorutils.main:main
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python {{ python }}
    - setuptools
    - biopython
    - pandas
    - pip
  run:
    - python {{ python }}
    - biopython
    - pandas

test:
  imports:
    - predectorutils
  commands:
    - predutils --help

about:
  home: "{{ url }}"
  license: "Apache License 2.0"
  license_family: APACHE
  license_file: "LICENSE"
  summary: "{{ description }}"
  doc_url: "{{ url }}"
  dev_url: "{{ url }}"

extra:
  maintainers:
    - Darcy Jones <darcy.a.jones@postgrad.curtin.edu.au>
  recipe-maintainers:
    - darcyabjones
